title: "F1 en estado puro"
description: "Conocimientos básicos del mejor deporte del mundo"
author: "Íñigo Fernández del Campo Viu"
url: "https://inigoloo.github.io"
baseurl: "/blog-jekyll"
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag



# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Collections defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Íñigo Fernández del Campo Viu"
      image: /assets/img/placeholder.jpg
